# ---------------- DATABASE ----------------
DB_USER = "postgres.njuzzesjniitrvaumfph"
DB_PASSWORD = "ONYESO080658"
DB_HOST = "aws-1-eu-central-1.pooler.supabase.com"
DB_PORT = "6543"
DB_NAME = "postgres"

[EMAIL]
EMAIL_USER = "alabiwinner9@gmail.com"
EMAIL_PASS = "svzg yqoz xpvi hupa"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465

[ADMIN]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "Booky123"
ADMIN_2FA = "080658"